// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpftffJHEYfUn6oXgcjcVwpOuHb1twJZI',
    appId: '1:202521412885:web:686151bc398b7deddb151c',
    messagingSenderId: '202521412885',
    projectId: 'kompanyon-94c73',
    authDomain: 'kompanyon-94c73.firebaseapp.com',
    storageBucket: 'kompanyon-94c73.appspot.com',
    measurementId: 'G-TGPCG1CSMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmc7w0_MNVCQ81Z6Yg19z3YxyqQ37NO38',
    appId: '1:202521412885:android:47381b13130e2043db151c',
    messagingSenderId: '202521412885',
    projectId: 'kompanyon-94c73',
    storageBucket: 'kompanyon-94c73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkySJr1U1CPwIaw2R8HGB7sJWSudkPfKI',
    appId: '1:202521412885:ios:53c88d2759313627db151c',
    messagingSenderId: '202521412885',
    projectId: 'kompanyon-94c73',
    storageBucket: 'kompanyon-94c73.appspot.com',
    iosBundleId: 'com.example.kompanyonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkySJr1U1CPwIaw2R8HGB7sJWSudkPfKI',
    appId: '1:202521412885:ios:53c88d2759313627db151c',
    messagingSenderId: '202521412885',
    projectId: 'kompanyon-94c73',
    storageBucket: 'kompanyon-94c73.appspot.com',
    iosBundleId: 'com.example.kompanyonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpftffJHEYfUn6oXgcjcVwpOuHb1twJZI',
    appId: '1:202521412885:web:af731a4acecfc603db151c',
    messagingSenderId: '202521412885',
    projectId: 'kompanyon-94c73',
    authDomain: 'kompanyon-94c73.firebaseapp.com',
    storageBucket: 'kompanyon-94c73.appspot.com',
    measurementId: 'G-3WMQSB12FV',
  );
}
